### ISSUE TITLE
Make plugin slug unique to avoid confusion

### ISSUE THREAD

**Issue by justanotheranonymoususer** [r-a-y/unlisted-posts#7]
Here's how it looks for me in the latest version. Why is that and how to use the plugin now?

![image](https://user-images.githubusercontent.com/5781692/101918207-c25cd700-3bd1-11eb-9f9d-28906c37a410.png)

**Comment by justanotheranonymoususer** [comment]
Never mind, I updated to latest `develop` version and it worked. It worked before, I think Wordpress just "updated" the plugin from v1.0.0 to v0.2-beta. Perhaps it's worth updating it in Wordpress website?

![image](https://user-images.githubusercontent.com/5781692/101921959-3ac59700-3bd6-11eb-83c6-eeec13577735.png)

**Comment by r-a-y** [comment]
Hi, my plugin isn't on the wordpress.org repo. That plugin is different than mine.

Because the wordpress.org plugin uses the same plugin slug as mine, that plugin takes precedence in the update system. My advice is to turn off auto-updates, so the plugin doesn't update and to subscribe to Github notifications so you are notified of new commits.

**Comment by justanotheranonymoususer** [comment]
Oh, heck. So maybe publish it, or at least use a unique slug?

**Comment by r-a-y** [comment]
Sorry, I don't plan on publishing on wordpress.org for now. You can change the slug yourself for this plugin. The plugin should still function okay.

**Comment by justanotheranonymoususer** [comment]
OK, I'll rename it. I had my dose of confusion, but to prevent other users from getting one, I'd still consider to change the slug. My 2¢. In any case, thanks for the plugin.

**Comment by r-a-y** [comment]
I've changed the slug to `unlisted`.
